### ISSUE TITLE
(documentation) self signed certificates

### ISSUE THREAD

**Issue by capc0** [GregaVrbancic/docker-netextender#1]
in case someone else struggles due to the error

``` 
2022-03-15T07:46:44.829166768Z There is a problem with the site's security certificate.
2022-03-15T07:46:44.829180264Z Warning: self signed certificate
```

it is possible to add `--always-trust` in `scripts/entrypoint.sh` to workaround the certificate check

**Comment by GregaVrbancic** [comment]
Hi @capc0, thanks for sharing this solution. I will try to prepare an improved version of entrypoint.sh script which would add --always-trust flag based on whether environmental variable ALWAYS_TRUST is set to true or not.
